name: Run integration tests

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: aws-actions/setup-sam@v2
          with:
            use-installer: true
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4.0.2
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            role-session-name: ${{ secrets.ROLE_SESSION_NAME }}
            aws-region: ${{ secrets.AWS_REGION }}
        - name: deploy stack
          id: deploy_stack
          env:
            AWS_REGION: ${{ secrets.AWS_REGION }}
          run: |
            randomId=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
            stackName="aws-lambda-rust-integ-test-$randomId"
            echo "STACK_NAME=$stackName" >> "$GITHUB_OUTPUT"
            echo "Stack name = $stackName"

            sam build --beta-features
            sam validate
            sam deploy --stack-name "${stackName}" --parameter-overrides "ParameterKey=SecretToken,ParameterValue=${{ secrets.SECRET_TOKEN }}" --no-confirm-changeset

            TEST_ENDPOINT=$(sam list stack-outputs --stack-name "${stackName}" --output json | jq -r '.[] | .OutputValue')
            echo "TEST_ENDPOINT=$TEST_ENDPOINT" >> "$GITHUB_OUTPUT"
        - name: run test
          env:
            SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
            TEST_ENDPOINT: ${{ steps.deploy_stack.outputs.TEST_ENDPOINT }}
          run: cargo test

        - name: cleanup
          if: always()
          env:
            AWS_REGION: ${{ secrets.AWS_REGION }}
            STACK_NAME: ${{ steps.deploy_stack.outputs.STACK_NAME }}
          run: sam delete --stack-name "${STACK_NAME}" --no-prompts
